Migration to version 6.40.5

diff --git a/docker/run b/docker/run
--- a/docker/run
+++ b/docker/run
@@ -6,6 +6,7 @@ progdir=${0%/*}
 if [ "$progdir" = "$program" ]; then progdir="."; fi
 if [ "$progdir" = "." ]; then progdir="$PWD"; fi
 parent=$(dirname $progdir)
+if [ "$parent" = "." ]; then parent="$PWD"; fi
 
 # ----------------------------------------------------------------------
 function usage() {
@@ -52,7 +53,7 @@ EOF
 
 # ----------------------------------------------------------------------
 function die() {
-    echo -e "\n$program: error: $*" > /dev/stderr
+    echo -e "\n$program: error: $*" >&2
     exit 1
 }
 
@@ -73,10 +74,17 @@ trap 'echo "$program($LINENO): Command failed with error code $? ([$$] $0 $*)"; 
 # Option parsing
 
 # Options
-shortopts=dhi:vVu:m:
-longopts=download-data,help,ietfdb-url=,verbose,version,user=,mysqldata=,
+shortopts=dhi:m:Mp:r:t:vVu:
+longopts=download-data,help,ietfdb-url=,mysqldata=,no-mysqldir,port=,docker-repo=,tag=,verbose,version,user=,
 
 # Default values
+MYSQLDIR=$parent/data/mysql
+FILEDIR=$parent/../data/
+PORT=8000
+REPO="ietf/datatracker-environment"
+TAG=$(basename $(svn info $parent | grep ^URL | awk '{print $2}'))
+DBURL=https://www.ietf.org/lib/dt/sprint/ietf_utf8.bin.tar.bz2
+WHO=$(whoami)
 
 if   [ "$(uname)" = "Linux" ]; then
     args=$(getopt -o "$shortopts" --long "$longopts" -n '$program' -- $SV "$@")
@@ -95,9 +103,13 @@ while true ; do
     case "$1" in
 	-d| --download-data) DOWNLOAD=1;;	# Download and set up the database files
 	-h| --help)	usage; exit;;		# Show this help, then exit
-	-i| --ietfdb-url) URL=$2; shift;;	# Use an alternative database tarball URL
-	-m| --mysqldir)	MYSQLDIR=$2; shift;;	# Set the desired location for MySQL's database files
-	-u| --user)	WHO=$2; shift;;		# Run container as someone else than $USER
+	-f| --filedir)	FILEDIR=$2; shift;;	# Set the desired location of drafts, charters etc.
+	-i| --ietfdb-url)	DBURL=$2; shift;;	# Use an alternative database tarball URL
+	-m| --mysqldir)	MYSQLDIR=$2; shift;;	# Set the desired location of MySQL's database files
+	-p| --port)	PORT=$2; shift;;	# Bind the container's port 8000 to external port PORT
+	-r| --docker-repo)	REPO=$2; shift;;	# Use the given docker repository, instead of the default
+	-t| --tag)	TAG=$2; shift;;		# Use this docker image tag, instead of the svn branch name
+	-u| --user)	WHO=$2; shift;;		# Run the container as the specified user
 	-v| --verbose)	VERBOSE=1;;		# Be more talkative
 	-V| --version)	version; exit;;		# Show program version, then exit
 	--)		shift; break;;
@@ -109,32 +121,119 @@ done
 # ----------------------------------------------------------------------
 # The program itself
 
-docker ps | grep -q levkowetz/datatracker:latest && die \
-"It seems that another docker container is already running the
-image 'levkowetz/datatracker:latest' -- but only one MySQL instance can bind
-to the database files at a time.  Quitting."
+if [ "$(uname)" != "Linux" ]; then
+    if [ "$(uname)" = "Darwin" ]; then
+	APP="/Applications/Docker.app"
+	CMD="open -a"
+    else
+	die "This script does not have support for your architecture ($(uname)); sorry :-("
+    fi
+    if [ -n "$(type -p docker-machine)" ]; then
+	machine=$(type -p docker-machine)
+    else
+	die "Could not find boot2docker or docker-machine -- you need to set one of those before running this script."
+    fi
+else
+    die "Didn't expect to run this script on Linux -- are you inside docker?"
+fi
 
-[ -n "$WHO" ]		|| WHO=$(whoami)
-[ -n "$MYSQLDIR" ]	|| MYSQLDIR=$parent/data/mysql
-[ -n "$URL"]		|| URL=https://www.ietf.org/lib/dt/sprint/ietf_utf8.bin.tar.bz2
+
+if [ -e "$APP" ]; then
+    info=$(docker info 2>&1 || true)
+    if ! docker info 1> /dev/null 2>&1; then
+	echo -e "The docker VM doesn't seem to be running; docker info gave:\n  $info"
+	echo "Will attempt to start docker by doing '\$ $CMD $APP':"
+	$CMD $APP
+	declare -i count
+	printf "Waiting for docker engine .."
+	while true; do
+	    printf "."
+	    sleep 2
+	    if docker info >/dev/null 2>&1; then break; fi
+	    count=$(( $count + 1))
+	    if [ $count -gt 10 ]; then
+		die "No contact with docker engine; bailing out."
+	    fi
+	done
+    fi
+    URL="http://localhost:$PORT/"
+else
+    if [ $($machine status default | tr "A-Z" "a-z" ) != "running" ]; then
+	echo "The docker VM doesn't seem to be running; will attempt to start it by doing '\$ $machine start':"
+	$machine start || die "Failed taking up the Docker VM"
+    fi
+
+    if [ -f "$machine" ]; then
+	if [ $($machine status default | tr "A-Z" "a-z") = "running" ]; then
+	    tmpfile=$(mktemp docker.run.XXXXXXXX)
+	    if $machine env 2>/dev/null | grep  DOCKER_ > $tmpfile; then
+		mv $tmpfile ~/.docker-info
+	    elif printenv | grep  DOCKER_ > $tmpfile; then
+		mv $tmpfile ~/.docker-info
+	    else
+		rm $tmpfile
+		die "Failed setting the appropriate DOCKER_* environment variables."
+	    fi
+	    . ~/.docker-info
+	else
+	    rm -f ~/.docker-info
+	fi
+	ip=$($machine ip)
+	URL="http://$ip:$PORT/"
+    fi
+fi
+
+echo ""
+echo "Starting a docker container for '$TAG'."
+
+docker ps | grep -q $REPO:$TAG && die \
+"It seems that another docker container is already running the
+image '$REPO:$TAG'.  Continuing here can cause various problems,
+such as changes from within the container being saved from different
+containers to the same image, overwriting earlier changes, and
+multiple containers trying to use the same database files.  Better
+to bail out here.  Quitting."
 
 if [ -n "$DOWNLOAD" ]; then
     (
 	cd $(dirname $MYSQLDIR)
-	wget -N $URL && tar xjf ietf_utf8.bin.tar.bz2 && chmod -R go+rwX mysql
+	wget -N $DBURL && tar xjf ietf_utf8.bin.tar.bz2 && chmod -R go+rwX mysql
     )
     [ -d "$MYSQLDIR" ] || die "The download seems to have failed; still no $MYSQLDIR.  Giving up."
 else
     [ -d "$MYSQLDIR" ] || die "Expected $MYSQLDIR to exist, but it\ndidn't.  Use '$program -d' to download and unpack the database."
 fi
 
-docker run -ti -p 8000:8000 -v $HOME:/home/$WHO -v $MYSQLDIR:/var/lib/mysql -e USER=$WHO -e DATADIR=${parent#$HOME/}/data levkowetz/datatracker:latest
+if ! docker images $REPO | grep -q $TAG; then
+    echo "Fetching docker image '$REPO:$TAG'"
+    if ! docker pull $REPO:$TAG; then
+	docker pull $REPO:latest || die "Failed to pull down the '$REPO:latest' docker image"
+	id=$(docker images $REPO | grep latest  | awk '{print $3}')
+	echo "Tagging $REPO:latest as $REPO:$TAG for use as environment for this branch."
+	docker tag $id $REPO:$TAG
+    fi
+fi
 
+echo -e "\nThe web interface for 'runserver' should appear on $URL\n"
+if [ -z "$MYSQLDIR" ]; then
+    docker run -ti -p $PORT:8000 -v $HOME:/home/$WHO                            \
+	-e USER=$WHO -e DATADIR=${parent#$HOME/}/data -e CWD=${PWD#$HOME/}	\
+	-e TAG=$TAG -e FILEDIR=${FILEDIR#$HOME}	\
+	$REPO:$TAG "$@"
+else
+    docker run -ti -p $PORT:8000 -v $HOME:/home/$WHO -v $MYSQLDIR:/var/lib/mysql\
+	-e USER=$WHO -e DATADIR=${parent#$HOME/}/data -e CWD=${PWD#$HOME/}	\
+	-e TAG=$TAG -e FILEDIR=${FILEDIR#$HOME}	\
+	$REPO:$TAG "$@"
+fi
+
+echo ""
 echo "Committing changes in the container to an image:"
 latest=$(docker ps -lq)
-docker commit $latest levkowetz/datatracker:latest
+docker commit $latest $REPO:$TAG
 
+echo ""
 echo "Cleaning up containers and images"
 docker rm $latest
-docker rmi -f $(docker images -f dangling=true -q)
+docker images -f dangling=true -q | xargs docker rmi -f
 
